name: Actualizar Resultados Lotería

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

# ¡Esta es la línea mágica que apaga la advertencia!
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  actualizar:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar librerías
        run: pip install requests beautifulsoup4

      - name: Ejecutar el Robot
        run: python robot.py

      - name: Guardar los nuevos números
        run: |
          git config --global user.name "Robot LotoAlDia"
          git config --global user.email "robot@lotoaldia.com"
          git add resultados.json
          git commit -m "Actualizando resultados diarios" || exit 0
          git push
